/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts INT NOT NULL,
    neutered BOOLEAN NOT NULL,
    weight_kg DECIMAL NOT NULL
);
ALTER TABLE animals ADD species varchar(100);

CREATE TABLE owners (
    id BIGSERIAL NOT NULL
    full_name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE species (
    id BIGSERIAL NOT NULL
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);


ALTER TABLE animals;
DROP COLUMN species;
ALTER TABLE animals;
ADD COLUMN species_id INTEGER;
ADD CONSTRAINT species_key FOREIGN KEY (species_id) REFERENCES species(id);
ON DELETE CASCADE;

ALTER TABLE animals;
ADD COLUMN owner_id INTEGER;
ADD CONSTRAINT owners_key FOREIGN KEY (owner_id) REFERENCES owners(id);
ON DELETE CASCADE;

CREATE TABLE vets (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  age INTEGER,
  date_of_graduation DATE,
  PRIMARY KEY (id)
);

CREATE TABLE specializations (
  vet_id INTEGER,
  species_id INTEGER,
  PRIMARY KEY (vet_id, species_id),
  FOREIGN KEY (vet_id) REFERENCES vets(id)
  ON DELETE CASCADE,
  FOREIGN KEY (species_id) REFERENCES species(id)
  ON DELETE CASCADE
);

CREATE TABLE visits (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  animal_id INTEGER,
  vet_id INTEGER,
  date_of_visit DATE,
  PRIMARY KEY (id),
  FOREIGN KEY (animal_id) REFERENCES animals(id)
  ON DELETE CASCADE,
  FOREIGN KEY (vet_id) REFERENCES vets(id)
  ON DELETE CASCADE
);
ALTER TABLE visits DROP CONSTRAINT visits_pkey; 
ALTER TABLE visits DROP COLUMN id;
ALTER TABLE visits ALTER COLUMN animal_id SET NOT NULL;
ALTER TABLE visits ALTER COLUMN vet_id SET NOT NULL,ALTER COLUMN date_of_visit SET NOT NULL;
CREATE INDEX animal_idx ON visits(animal_id); 
CREATE INDEX vet_idx ON visits(vet_id); 

ALTER TABLE owners ALTER COLUMN age DROP NOT NULL;
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

